# -*- coding: utf-8 -*-
"""ain1001_hw1_2367143.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ca0plHRlnIbk-cWeej-wlTl259DchV_A
"""

# Task 1
def task_1_type_explorer():
  print("Task 1 Type Explorer")
  age_str= input("Enter your age: ")
  height_str= input("Enter your height: ")
  name_str= input("Enter your name: ")

  age= int(age_str)
  height= float(height_str)
  full_name= str(name_str)

  print(full_name)
  print(age)
  print(height)
  pass

# Task 2
def task_2_unit_mini_converter():
  print("Task 2 Unit Mini Conventer")
  celcius= input("Enter the temperature in celcius: ")
  celcius= int(celcius)
  fahrenheit= (celcius * 9/5)+32
  kelvin= (celcius + 273)
  print(fahrenheit)
  print(kelvin)
  if celcius < 0:
      print("freezing")
  elif 0 < celcius < 25:
      print("cool")
  elif celcius > 25:
      print("hot")
      pass

#task 3 a
def task_3_loop_practice_pack():
  print("Task 3 Loop Practice Pack")
  n=int(input("pozitif bir n değeri girin: "))
  toplam= 0
  i= 1

  while i<= n:
    toplam += i
    i+= 1
  print ("1'den " + str(n) + "'e kadar olan sayıların toplamı : " +str(toplam))


#b
  n=int(input("pozitif bir n değeri girin: "))
  f= 1

  for i in range (1, n+1):
    f *= i

  print(n, "sayısının faktöriyeli: ", f)

#c
  k= int(input("kaç terim yazalım (k): "))

  fibonacci = [0,1]
  for i in range (2,k):
    new = fibonacci [i-1] + fibonacci [i-2]
    fibonacci.append(new)

  print("ilk", k, "fibonacci sayısı: ")
  print(fibonacci[:k])
  pass

#task 4
def task_4_list_of_grades_toolkit():
  print("Task 4 List of Grades Toolkit")
  m= int(input("sınıfta kaç kişi var: "))
  grades = []
  for i in range(m):
    print("notu girin: ", i+1, ":", end=" ")
    g = int(input())
    grades.append(g)
    i += 1

  count = 0
  for _ in grades:
    count += 1

  min_grade = grades[0]
  max_grade = grades[0]
  for g in grades:
    if g < min_grade:
      min_grade = g
    if g > max_grade:
      max_grade = g

  total = 0
  for g in grades:
    total += g

  average = total / count

  print("Sayı:" , count)
  print("En yüksek not:" , max_grade)
  print("En düşük not:" , min_grade)
  print("Ortalama not:" , average)

  target = int(input())
  found_indices = []
  i = 0
  while i < count:
    if grades [i] == target:
      found_indices.append(i)
    i += 1

  if len(found_indices) == 0:
    print("Aranan değer listede yok.")
  else:
    print("Aranan değer listede: " + str(found_indices))


  unique_grades = []
  for g in grades:
    exists = False
    for u in unique_grades:
      if g == u:
        exists = True
        break
    if not exists:
       unique_grades.append(g)


  bonus_grades = []
  for g in grades:
      new_grade = g + 5
      if new_grade > 100:
          new_grade = 100
      bonus_grades.append(new_grade)
      pass

  print("+5 bonus puandan sonra notlarınız: ", bonus_grades)


def main_menu():
  while True:
    print("AIN1001 Homework Menu")

    choice = input("Select: ").strip()
    if choice == "1":
      print("Task 1 çalıştırılıyor.")
      task_1_type_explorer()

    elif choice == "2":
      print("Task 2 çalıştırılıyor.")
      task_2_unit_mini_converter()

    elif choice == "3":
      print("Task 3 çalıştırılıyor.")
      task_3_loop_practice_pack()
    elif choice == "4":
      print("Task 4 çalıştırılıyor.")
      task_4_list_of_grades_toolkit()
    elif choice == "5":
      print("Çıkış yapılıyor.")
      break

    else:
      print("Geçersiz seçim. Lütfen tekrar deneyin.")



if __name__ == "__main__":
    main_menu()